application: earth-pressure
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /sitemap\.xml
  static_files: sitemap.xml
  upload: sitemap\.xml

- url: /static/css
  static_dir: static/css
  expiration: "7d"

- url: /static/scripts
  static_dir: static/scripts
  expiration: "7d"
  
- url: /static/images
  static_dir: static/images
  expiration: "7d"  
  
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest